import type { AdminConfig, Exercise, Routine } from "./types";

const GIF = (folder: string, slug: string) =>
  `https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/${folder}/${slug}.gif`;

export const DEFAULT_EXERCISES: Exercise[] = [
  {
    id: "bench-press",
    name: "Supino Reto com Barra",
    group: "Peito",
    muscle: "Peitoral Maior Esternal",
    videoUrl: GIF("chest", "barbell-bench-press"),
    equivalentId: "peck-deck",
    cue: "Controle a fase excêntrica em 2 segundos e mantenha o cotovelo a 45 graus em relação ao tronco.",
    steps: [
      "Deite no banco com os olhos alinhados sob a barra e escápulas retraídas.",
      "Pegada levemente mais larga que os ombros, punhos neutros sobre o antebraço.",
      "Desça a barra até a linha do mamilo em 2 segundos, sem quicar no peito.",
      "Empurre a barra em leve diagonal para trás até estender os cotovelos.",
    ],
    mistakes: [
      "Soltar as escápulas e perder a base estável do tronco.",
      "Abrir os cotovelos a 90 graus, sobrecarregando o ombro.",
      "Descer rápido demais e usar impulso do peito.",
    ],
  },
  {
    id: "incline-db-press",
    name: "Supino Inclinado com Halteres",
    group: "Peito",
    muscle: "Peitoral Superior Clavicular",
    videoUrl: GIF("chest", "incline-dumbbell-bench-press"),
    equivalentId: "bench-press",
    cue: "Banco a 30 graus é suficiente: acima disso o deltoide assume o trabalho.",
    steps: [
      "Regule o banco entre 30 e 35 graus.",
      "Suba os halteres com os punhos alinhados aos cotovelos.",
      "Desça até os halteres na linha da clavícula.",
      "Aproxime os halteres sem batê-los no topo.",
    ],
    mistakes: ["Inclinação excessiva do banco.", "Arquear a lombar para empurrar mais carga."],
  },
  {
    id: "peck-deck",
    name: "Crossover / Peck Deck na Máquina",
    group: "Peito",
    muscle: "Peitoral Maior (Estímulo Isolado)",
    videoUrl: GIF("chest", "butterfly"),
    equivalentId: "bench-press",
    cue: "Pause 1 segundo na contração máxima antes de retornar, mantendo a lombar apoiada.",
    steps: [
      "Ajuste o assento para as manoplas ficarem na altura do meio do peito.",
      "Mantenha os pés firmes no chão e o abdômen contraído.",
      "Aproxime os braços até quase tocar as mãos, sem travar o cotovelo.",
      "Retorne controlado até sentir alongamento no peitoral.",
    ],
    mistakes: [
      "Assento alto demais recrutando ombro no lugar do peito.",
      "Soltar a carga de volta sem controle.",
    ],
  },
  {
    id: "lat-pulldown",
    name: "Puxada Alta no Pulley",
    group: "Costas",
    muscle: "Grande Dorsal",
    videoUrl: GIF("back", "lat-pulldown"),
    equivalentId: "bent-over-row",
    cue: "Puxe com os cotovelos em direção ao bolso, sem inclinar o tronco além de 15 graus.",
    steps: [
      "Fixe as coxas no apoio e segure a barra pronada.",
      "Deprima as escápulas antes de puxar.",
      "Puxe até a barra na linha da clavícula.",
      "Suba controlado permitindo alongamento total.",
    ],
    mistakes: ["Puxar com bíceps antes das escápulas.", "Balançar o tronco para vencer a carga."],
  },
  {
    id: "seated-row",
    name: "Remada Baixa no Triângulo (Polia)",
    group: "Costas",
    muscle: "Dorsal e Rombóides",
    videoUrl: GIF("back", "seated-cable-row"),
    equivalentId: "lat-pulldown",
    cue: "Aperte as escápulas por 1 segundo no fim de cada repetição.",
    steps: [
      "Sentado com joelhos semiflexionados, tronco neutro.",
      "Puxe o triângulo até o abdômen.",
      "Aproxime as escápulas ao final.",
      "Retorne alongando sem curvar a lombar.",
    ],
    mistakes: ["Balançar o tronco para frente e para trás.", "Curvar a coluna no retorno."],
  },
  {
    id: "bent-over-row",
    name: "Remada Curvada com Barra",
    group: "Costas",
    muscle: "Costas Completa",
    videoUrl: GIF("back", "barbell-bent-over-row"),
    equivalentId: "seated-row",
    cue: "Tronco a 45 graus e coluna rígida: o movimento é do cotovelo, não da lombar.",
    steps: [
      "Pés na largura do quadril, quadril para trás e tronco inclinado a 45 graus.",
      "Segure a barra pronada um pouco mais larga que os ombros.",
      "Puxe a barra em direção ao abdômen inferior.",
      "Desça controlado até a extensão completa dos braços.",
    ],
    mistakes: ["Arredondar a lombar.", "Usar impulso de tronco subindo o peito a cada repetição."],
  },
  {
    id: "barbell-squat",
    name: "Agachamento Livre",
    group: "Pernas",
    muscle: "Quadríceps e Glúteos",
    videoUrl: GIF("legs", "barbell-squat"),
    equivalentId: "leg-press",
    cue: "Joelho passa à frente do pé: isso é normal e protege o quadril se o tronco ficar rígido.",
    steps: [
      "Barra apoiada no trapézio, pés na largura dos ombros.",
      "Inspire, contraia o abdômen e desça em 2 segundos.",
      "Desça até coxa paralela ou abaixo, se a mobilidade permitir.",
      "Suba empurrando o chão com o pé inteiro.",
    ],
    mistakes: [
      "Levantar o quadril primeiro e curvar a lombar.",
      "Joelhos colapsando para dentro.",
    ],
  },
  {
    id: "leg-press",
    name: "Leg Press 45",
    group: "Pernas",
    muscle: "Quadríceps",
    videoUrl: GIF("legs", "leg-press"),
    equivalentId: "barbell-squat",
    cue: "Pés um pouco mais baixos na plataforma aumentam o estímulo no quadríceps.",
    steps: [
      "Costas e quadril totalmente apoiados no encosto.",
      "Destrave e desça controlado em 2 segundos.",
      "Pare quando o joelho chegar a cerca de 90 graus.",
      "Empurre sem travar completamente o joelho.",
    ],
    mistakes: ["Descolar o quadril do encosto.", "Amplitude curta com carga excessiva."],
  },
  {
    id: "leg-extension",
    name: "Cadeira Extensora",
    group: "Pernas",
    muscle: "Reto Femoral / Quadríceps",
    videoUrl: GIF("legs", "leg-extension"),
    equivalentId: "leg-press",
    cue: "Segure 1 segundo na extensão máxima para maximizar a contração do quadríceps.",
    steps: [
      "Ajuste o encosto para o joelho alinhar com o eixo da máquina.",
      "Rolo apoiado acima do tornozelo, mãos nas alças.",
      "Estenda até a contração máxima sem tirar o quadril do assento.",
      "Retorne em 3 segundos resistindo à carga.",
    ],
    mistakes: ["Impulsionar com o tronco.", "Deixar o peso cair na volta."],
  },
  {
    id: "leg-curl",
    name: "Mesa Flexora",
    group: "Pernas",
    muscle: "Posteriores de Coxa",
    videoUrl: GIF("legs", "lying-leg-curl"),
    equivalentId: "bulgarian-split-squat",
    cue: "Mantenha o quadril colado no banco durante toda a série.",
    steps: [
      "Ajuste o rolo acima do tendão de Aquiles.",
      "Segure as alças e mantenha o quadril fixo.",
      "Flexione até a contração máxima.",
      "Retorne em 3 segundos.",
    ],
    mistakes: ["Levantar o quadril no esforço.", "Retornar deixando o peso cair."],
  },
  {
    id: "bulgarian-split-squat",
    name: "Agachamento Búlgaro (com Halteres)",
    group: "Pernas",
    muscle: "Glúteos e Quadríceps Unilateral",
    videoUrl: GIF("legs", "dumbbell-single-leg-split-squat"),
    equivalentId: "barbell-squat",
    cue: "Tronco levemente à frente aumenta o glúteo; tronco vertical prioriza o quadríceps.",
    steps: [
      "Apoie o pé de trás no banco e afaste o pé da frente cerca de dois passos.",
      "Segure um halter em cada mão com os braços estendidos.",
      "Desça verticalmente até o joelho de trás quase tocar o chão.",
      "Suba empurnando o chão com o pé da frente, sem impulso.",
    ],
    mistakes: ["Passo curto sobrecarregando o joelho.", "Perder o equilíbrio girando o quadril."],
  },
  {
    id: "db-shoulder-press",
    name: "Desenvolvimento com Halteres",
    group: "Ombro",
    muscle: "Deltoide Anterior",
    videoUrl: GIF("shoulders", "dumbbell-shoulder-press"),
    equivalentId: "lateral-raise",
    cue: "Costelas para baixo e abdômen firme: evita compensar arqueando a lombar.",
    steps: [
      "Sentado com apoio de tronco, halteres na altura das orelhas.",
      "Punhos alinhados aos cotovelos e olhar à frente.",
      "Empurre para cima até quase estender, sem batê-los.",
      "Desça em 2 segundos até 90 graus de flexão.",
    ],
    mistakes: ["Arquear a lombar para empurrar mais carga.", "Amplitude curta na descida."],
  },
  {
    id: "lateral-raise",
    name: "Elevação Lateral com Halteres",
    group: "Ombro",
    muscle: "Deltoide Lateral",
    videoUrl: GIF("shoulders", "dumbbell-lateral-raise"),
    equivalentId: "db-shoulder-press",
    cue: "Lidere o movimento com o cotovelo, não com a mão, e pare na linha dos ombros.",
    steps: [
      "Em pé, leve inclinação de tronco à frente e cotovelos semiflexionados.",
      "Eleve os braços pelas laterais liderando com os cotovelos.",
      "Pare na altura dos ombros e segure meio segundo.",
      "Desça em 2 segundos resistindo à gravidade.",
    ],
    mistakes: [
      "Usar impulso de tronco (balanço) para subir a carga.",
      "Elevar acima da linha do ombro e recrutar trapézio.",
    ],
  },
  {
    id: "reverse-fly",
    name: "Crucifixo Invertido / Peck Deck Invertido",
    group: "Ombro",
    muscle: "Deltoide Posterior",
    videoUrl: GIF("shoulders", "reverse-fly"),
    equivalentId: "lateral-raise",
    cue: "Pense em abrir os braços com o cotovelo fixo, sem juntar as escápulas com força.",
    steps: [
      "Peito apoiado no encosto e manoplas na altura dos ombros.",
      "Cotovelos levemente flexionados e fixos.",
      "Abra os braços até a linha do tronco.",
      "Retorne controlado mantendo tensão.",
    ],
    mistakes: ["Transformar em remada puxando com o dorsal.", "Encolher os ombros na abertura."],
  },
  {
    id: "triceps-rope",
    name: "Tríceps Pulley na Polia (Corda)",
    group: "Tríceps",
    muscle: "Tríceps (Cabeça Lateral)",
    videoUrl: GIF("arms", "cable-rope-pushdown"),
    equivalentId: "triceps-testa",
    cue: "Cotovelos colados ao tronco: apenas o antebraço se move.",
    steps: [
      "Segure a corda com pegada neutra e cotovelos junto ao corpo.",
      "Estenda os cotovelos abrindo a corda no final.",
      "Contraia 1 segundo com o braço totalmente estendido.",
      "Retorne até 90 graus de flexão.",
    ],
    mistakes: ["Afastar os cotovelos do tronco.", "Inclinar o corpo para empurrar a carga."],
  },
  {
    id: "triceps-testa",
    name: "Tríceps Testa",
    group: "Tríceps",
    muscle: "Tríceps (Cabeça Longa)",
    videoUrl: GIF("arms", "cable-lying-triceps-extension"),
    equivalentId: "triceps-rope",
    cue: "Alongue bem a cabeça longa: desça até sentir tensão atrás do braço.",
    steps: [
      "Deitado no banco, braços apontados levemente para trás.",
      "Flexione os cotovelos levando a carga em direção à testa.",
      "Mantenha os cotovelos apontados para frente e fixos.",
      "Estenda sem travar bruscamente.",
    ],
    mistakes: ["Abrir os cotovelos lateralmente.", "Mover o braço todo em vez do antebraço."],
  },
  {
    id: "biceps-curl",
    name: "Rosca Direta com Barra W",
    group: "Bíceps",
    muscle: "Bíceps Braquial",
    videoUrl: GIF("arms", "ez-bar-curl"),
    equivalentId: "hammer-curl",
    cue: "Cotovelo travado na lateral do tronco; sem balanço de ombro.",
    steps: [
      "Pegada supinada na barra W, cotovelos junto ao corpo.",
      "Flexione até a contração máxima.",
      "Desça em 2 a 3 segundos.",
      "Estenda completamente antes da próxima repetição.",
    ],
    mistakes: ["Usar o tronco como alavanca.", "Parar antes da extensão completa."],
  },
  {
    id: "hammer-curl",
    name: "Rosca Martelo com Halteres",
    group: "Bíceps",
    muscle: "Braquiorradial e Bíceps",
    videoUrl: GIF("arms", "dumbbell-hammer-curl"),
    equivalentId: "biceps-curl",
    cue: "Pegada neutra durante todo o movimento: o punho não gira.",
    steps: [
      "Em pé, halteres com pegada neutra ao lado do corpo.",
      "Flexione mantendo o cotovelo fixo na lateral.",
      "Contraia 1 segundo no topo.",
      "Desça em 2 segundos até a extensão completa.",
    ],
    mistakes: ["Balançar o tronco para subir a carga.", "Girar o punho no meio do movimento."],
  },
];

const set = (reps: number, previous: string, count: number) =>
  Array.from({ length: count }, () => ({ reps, previous }));

export const DEFAULT_ROUTINE: Routine = {
  id: "meso-hipertrofia-01",
  name: "Hipertrofia Progressiva — Bloco A",
  createdAt: new Date("2026-09-01T08:00:00Z").toISOString(),
  mesocycle: "Mesociclo de Hipertrofia",
  week: 1,
  totalWeeks: 12,
  days: [
    {
      id: "seg",
      label: "Seg",
      focus: "Peito, Ombro Lateral & Tríceps",
      estimatedMinutes: "45-50 min",
      exercises: [
        { exerciseId: "bench-press", sets: set(10, "24 kg × 10", 4), restSeconds: 120 },
        { exerciseId: "incline-db-press", sets: set(12, "16 kg × 12", 4), restSeconds: 90 },
        { exerciseId: "lateral-raise", sets: set(15, "8 kg × 15", 4), restSeconds: 60 },
        { exerciseId: "triceps-rope", sets: set(12, "22 kg × 12", 4), restSeconds: 60 },
      ],
    },
    {
      id: "ter",
      label: "Ter",
      focus: "Costas, Dorsal & Bíceps",
      estimatedMinutes: "50-55 min",
      exercises: [
        { exerciseId: "lat-pulldown", sets: set(10, "45 kg × 10", 4), restSeconds: 120 },
        { exerciseId: "seated-row", sets: set(12, "40 kg × 12", 4), restSeconds: 90 },
        { exerciseId: "bent-over-row", sets: set(10, "40 kg × 10", 3), restSeconds: 120 },
        { exerciseId: "hammer-curl", sets: set(12, "12 kg × 12", 3), restSeconds: 60 },
      ],
    },
    {
      id: "qua",
      label: "Qua",
      focus: "Quadríceps & Glúteo",
      estimatedMinutes: "55-60 min",
      exercises: [
        { exerciseId: "barbell-squat", sets: set(8, "60 kg × 8", 4), restSeconds: 180 },
        { exerciseId: "leg-press", sets: set(12, "90 kg × 12", 3), restSeconds: 120 },
        { exerciseId: "leg-extension", sets: set(15, "35 kg × 15", 3), restSeconds: 75 },
        { exerciseId: "bulgarian-split-squat", sets: set(10, "14 kg × 10", 3), restSeconds: 90 },
      ],
    },
    {
      id: "qui",
      label: "Qui",
      focus: "Ombro Completo & Tríceps",
      estimatedMinutes: "40-45 min",
      exercises: [
        { exerciseId: "db-shoulder-press", sets: set(10, "18 kg × 10", 4), restSeconds: 90 },
        { exerciseId: "lateral-raise", sets: set(15, "8 kg × 15", 4), restSeconds: 60 },
        { exerciseId: "reverse-fly", sets: set(15, "15 kg × 15", 3), restSeconds: 60 },
        { exerciseId: "triceps-testa", sets: set(12, "14 kg × 12", 3), restSeconds: 75 },
      ],
    },
    {
      id: "sex",
      label: "Sex",
      focus: "Posterior de Coxa & Peito Alto",
      estimatedMinutes: "50-55 min",
      exercises: [
        { exerciseId: "leg-curl", sets: set(12, "30 kg × 12", 4), restSeconds: 90 },
        { exerciseId: "bulgarian-split-squat", sets: set(10, "16 kg × 10", 3), restSeconds: 90 },
        { exerciseId: "incline-db-press", sets: set(10, "18 kg × 10", 4), restSeconds: 90 },
        { exerciseId: "biceps-curl", sets: set(12, "20 kg × 12", 3), restSeconds: 60 },
      ],
    },
    {
      id: "sab",
      label: "Sáb",
      focus: "Full Body Metabólico",
      estimatedMinutes: "35-40 min",
      exercises: [
        { exerciseId: "leg-press", sets: set(15, "70 kg × 15", 3), restSeconds: 75 },
        { exerciseId: "seated-row", sets: set(15, "35 kg × 15", 3), restSeconds: 60 },
        { exerciseId: "peck-deck", sets: set(15, "28 kg × 15", 3), restSeconds: 60 },
        { exerciseId: "triceps-rope", sets: set(15, "18 kg × 15", 3), restSeconds: 45 },
      ],
    },
  ],
};

export const DEFAULT_CONFIG: AdminConfig = {
  apiKey: "",
  model: "gpt-4o-mini",
  systemPrompt: `Você é o Treinador HyperFlow Pro, especialista em fisiologia do exercício e periodização.
Regras científicas:
1. Monte mesociclos de 12 semanas com progressão de carga dupla (repetição e depois carga).
2. Volume semanal entre 10 e 20 séries por grupo muscular treinado.
3. Priorize exercícios compostos no início da sessão e isoladores no final.
4. Descanso: 120-180s para compostos pesados, 45-90s para isoladores.
5. Use apenas exercícios presentes no catálogo fornecido e respeite restrições articulares informadas.
6. Para cada exercício, inclua uma dica biomecânica curta e objetiva em português.`,
};

export const DAILY_QUOTES: string[] = [
  "A consistência silenciosa supera o entusiasmo barulhento. Hoje é dia de carga máxima.",
  "Você não precisa de motivação. Precisa de disciplina e de mais uma repetição limpa.",
  "O corpo obedece à mente que decidiu antes de entrar na academia.",
  "Dor controlada é informação. Dor descontrolada é aviso. Aprenda a diferença.",
  "Ninguém vê as séries que você fez às 6 da manhã. O espelho vê.",
  "Treine hoje o corpo que vai te carregar aos 70 anos.",
  "Volume sem técnica é apenas fadiga caríssima. Execute com precisão.",
  "O que é fácil hoje foi impossível há doze semanas. Continue.",
  "Descanso é parte do treino, não uma pausa nele.",
  "Cada repetição controlada é um voto para a pessoa que você quer ser.",
  "A carga na barra é honesta: ela só sobe quando você merece.",
  "Domine o básico até que o básico pareça arte.",
];
