import type { AdminConfig, Exercise, Routine } from "./types";

const V = (slug: string) => `https://cdn.hyperflowpro.app/media/exercises/${slug}.mp4`;

export const DEFAULT_EXERCISES: Exercise[] = [
  {
    id: "bench-press",
    name: "Supino Reto com Barra",
    group: "Peito",
    muscle: "Peitoral maior (porção esternal)",
    videoUrl: V("supino-reto-barra"),
    equivalentId: "machine-press",
    cue: "Controle a fase excêntrica em 2 segundos e mantenha o cotovelo a 45 graus em relação ao tronco.",
    steps: [
      "Deite no banco com os olhos alinhados sob a barra e escápulas retraídas.",
      "Pegada levemente mais larga que os ombros, punhos neutros sobre o antebraço.",
      "Desça a barra até a linha do mamilo em 2 segundos, sem quicar no peito.",
      "Empurre a barra em leve diagonal para trás até estender os cotovelos.",
    ],
    mistakes: [
      "Soltar as escápulas e perder a base estável do tronco.",
      "Abrir os cotovelos a 90 graus, sobrecarregando o ombro.",
      "Descer rápido demais e usar impulso do peito.",
    ],
  },
  {
    id: "machine-press",
    name: "Supino Máquina Convergente",
    group: "Peito",
    muscle: "Peitoral maior (porção medial)",
    videoUrl: V("supino-maquina-convergente"),
    equivalentId: "bench-press",
    cue: "Pause 1 segundo na contração máxima antes de retornar, mantendo a lombar apoiada.",
    steps: [
      "Ajuste o assento para as manoplas ficarem na altura do meio do peito.",
      "Mantenha os pés firmes no chão e o abdômen contraído.",
      "Empurre até quase estender, sem travar o cotovelo.",
      "Retorne controlado até sentir alongamento no peitoral.",
    ],
    mistakes: [
      "Assento alto demais recrutando ombro no lugar do peito.",
      "Soltar a carga de volta sem controle.",
    ],
  },
  {
    id: "incline-db-press",
    name: "Supino Inclinado com Halteres",
    group: "Peito",
    muscle: "Peitoral maior (porção clavicular)",
    videoUrl: V("supino-inclinado-halteres"),
    equivalentId: "machine-press",
    cue: "Banco a 30 graus é suficiente: acima disso o deltoide assume o trabalho.",
    steps: [
      "Regule o banco entre 30 e 35 graus.",
      "Suba os halteres com os punhos alinhados aos cotovelos.",
      "Desça até os halteres na linha da clavícula.",
      "Aproxime os halteres sem batê-los no topo.",
    ],
    mistakes: ["Inclinação excessiva do banco.", "Arquear a lombar para empurrar mais carga."],
  },
  {
    id: "lateral-raise",
    name: "Elevação Lateral com Halteres",
    group: "Ombro",
    muscle: "Deltoide lateral",
    videoUrl: V("elevacao-lateral-halteres"),
    equivalentId: "cable-lateral-raise",
    cue: "Lidere o movimento com o cotovelo, não com a mão, e pare na linha dos ombros.",
    steps: [
      "Em pé, leve inclinação de tronco à frente e cotovelos semiflexionados.",
      "Eleve os braços pelas laterais liderando com os cotovelos.",
      "Pare na altura dos ombros e segure meio segundo.",
      "Desça em 2 segundos resistindo à gravidade.",
    ],
    mistakes: [
      "Usar impulso de tronco (balanço) para subir a carga.",
      "Elevar acima da linha do ombro e recrutar trapézio.",
    ],
  },
  {
    id: "cable-lateral-raise",
    name: "Elevação Lateral no Cabo Unilateral",
    group: "Ombro",
    muscle: "Deltoide lateral",
    videoUrl: V("elevacao-lateral-cabo"),
    equivalentId: "lateral-raise",
    cue: "Tensão constante: o cabo mantém carga também na porção inicial do movimento.",
    steps: [
      "Posicione a polia na altura baixa e segure com a mão oposta.",
      "Afaste-se levemente para criar tensão inicial.",
      "Eleve o braço até a linha do ombro.",
      "Retorne lento sem deixar a placa tocar.",
    ],
    mistakes: ["Girar o tronco para ajudar.", "Amplitude curta perto do corpo."],
  },
  {
    id: "triceps-rope",
    name: "Tríceps Corda na Polia Alta",
    group: "Tríceps",
    muscle: "Tríceps braquial (cabeça lateral)",
    videoUrl: V("triceps-corda-polia"),
    equivalentId: "triceps-french",
    cue: "Cotovelos colados ao tronco: apenas o antebraço se move.",
    steps: [
      "Segure a corda com pegada neutra e cotovelos junto ao corpo.",
      "Estenda os cotovelos abrindo a corda no final.",
      "Contraia 1 segundo com o braço totalmente estendido.",
      "Retorne até 90 graus de flexão.",
    ],
    mistakes: ["Afastar os cotovelos do tronco.", "Inclinar o corpo para empurrar a carga."],
  },
  {
    id: "triceps-french",
    name: "Tríceps Francês Sentado",
    group: "Tríceps",
    muscle: "Tríceps braquial (cabeça longa)",
    videoUrl: V("triceps-frances-sentado"),
    equivalentId: "triceps-rope",
    cue: "Alongue bem a cabeça longa: desça até sentir tensão atrás do braço.",
    steps: [
      "Sentado com apoio de tronco, halter acima da cabeça.",
      "Flexione os cotovelos levando o peso atrás da cabeça.",
      "Mantenha os cotovelos apontados para frente.",
      "Estenda sem travar bruscamente.",
    ],
    mistakes: ["Abrir os cotovelos lateralmente.", "Perder o apoio lombar no banco."],
  },
  {
    id: "lat-pulldown",
    name: "Puxada Alta Pronada",
    group: "Costas",
    muscle: "Latíssimo do dorso",
    videoUrl: V("puxada-alta-pronada"),
    equivalentId: "pull-up",
    cue: "Puxe com os cotovelos em direção ao bolso, sem inclinar o tronco além de 15 graus.",
    steps: [
      "Fixe as coxas no apoio e segure a barra pronada.",
      "Deprima as escápulas antes de puxar.",
      "Puxe até a barra na linha da clavícula.",
      "Suba controlado permitindo alongamento total.",
    ],
    mistakes: ["Puxar com bíceps antes das escápulas.", "Balançar o tronco para vencer a carga."],
  },
  {
    id: "pull-up",
    name: "Barra Fixa Assistida",
    group: "Costas",
    muscle: "Latíssimo do dorso",
    videoUrl: V("barra-fixa-assistida"),
    equivalentId: "lat-pulldown",
    cue: "Peito para a barra: pense em levar o esterno, não o queixo.",
    steps: [
      "Ajuste o contrapeso da máquina assistida.",
      "Pegada pronada um pouco mais larga que os ombros.",
      "Suba levando o peito à barra.",
      "Desça em 3 segundos até a extensão completa.",
    ],
    mistakes: ["Amplitude parcial no topo.", "Encolher os ombros na subida."],
  },
  {
    id: "seated-row",
    name: "Remada Sentada na Polia",
    group: "Costas",
    muscle: "Trapézio médio e rombóides",
    videoUrl: V("remada-sentada-polia"),
    equivalentId: "lat-pulldown",
    cue: "Aperte as escápulas por 1 segundo no fim de cada repetição.",
    steps: [
      "Sentado com joelhos semiflexionados, tronco neutro.",
      "Puxe o triângulo até o abdômen.",
      "Aproxime as escápulas ao final.",
      "Retorne alongando sem curvar a lombar.",
    ],
    mistakes: ["Balançar o tronco para frente e para trás.", "Curvar a coluna no retorno."],
  },
  {
    id: "barbell-squat",
    name: "Agachamento Livre com Barra",
    group: "Pernas",
    muscle: "Quadríceps e glúteo máximo",
    videoUrl: V("agachamento-livre-barra"),
    equivalentId: "hack-squat",
    cue: "Joelho passa à frente do pé: isso é normal e protege o quadril se o tronco ficar rígido.",
    steps: [
      "Barra apoiada no trapézio, pés na largura dos ombros.",
      "Inspire, contraia o abdômen e desça em 2 segundos.",
      "Desça até coxa paralela ou abaixo, se a mobilidade permitir.",
      "Suba empurrando o chão com o pé inteiro.",
    ],
    mistakes: [
      "Levantar o quadril primeiro e curvar a lombar.",
      "Joelhos colapsando para dentro.",
    ],
  },
  {
    id: "hack-squat",
    name: "Agachamento no Hack",
    group: "Pernas",
    muscle: "Quadríceps (vasto lateral)",
    videoUrl: V("agachamento-hack"),
    equivalentId: "barbell-squat",
    cue: "Pés um pouco mais baixos na plataforma aumentam o estímulo no quadríceps.",
    steps: [
      "Costas totalmente apoiadas no encosto.",
      "Destrave e desça controlado em 2 segundos.",
      "Pare quando a coxa passar da paralela.",
      "Suba sem travar completamente o joelho.",
    ],
    mistakes: ["Descolar o quadril do encosto.", "Amplitude curta com carga excessiva."],
  },
  {
    id: "romanian-deadlift",
    name: "Levantamento Terra Romeno",
    group: "Pernas",
    muscle: "Isquiotibiais e glúteo",
    videoUrl: V("terra-romeno"),
    equivalentId: "leg-curl",
    cue: "Empurre o quadril para trás mantendo a barra rente à perna.",
    steps: [
      "Em pé, barra próxima ao corpo, joelhos levemente flexionados.",
      "Leve o quadril para trás descendo a barra pela perna.",
      "Pare quando sentir alongamento máximo no posterior.",
      "Volte contraindo o glúteo no topo.",
    ],
    mistakes: ["Arredondar a lombar.", "Transformar em agachamento flexionando muito o joelho."],
  },
  {
    id: "leg-curl",
    name: "Mesa Flexora",
    group: "Pernas",
    muscle: "Isquiotibiais",
    videoUrl: V("mesa-flexora"),
    equivalentId: "romanian-deadlift",
    cue: "Mantenha o quadril colado no banco durante toda a série.",
    steps: [
      "Ajuste o rolo acima do tendão de Aquiles.",
      "Segure as alças e mantenha o quadril fixo.",
      "Flexione até a contração máxima.",
      "Retorne em 3 segundos.",
    ],
    mistakes: ["Levantar o quadril no esforço.", "Retornar deixando o peso cair."],
  },
  {
    id: "biceps-curl",
    name: "Rosca Direta com Barra W",
    group: "Bíceps",
    muscle: "Bíceps braquial",
    videoUrl: V("rosca-direta-barra-w"),
    equivalentId: "incline-curl",
    cue: "Cotovelo travado na lateral do tronco; sem balanço de ombro.",
    steps: [
      "Pegada supinada na barra W, cotovelos junto ao corpo.",
      "Flexione até a contração máxima.",
      "Desça em 2 a 3 segundos.",
      "Estenda completamente antes da próxima repetição.",
    ],
    mistakes: ["Usar o tronco como alavanca.", "Parar antes da extensão completa."],
  },
  {
    id: "incline-curl",
    name: "Rosca Inclinada com Halteres",
    group: "Bíceps",
    muscle: "Bíceps braquial (cabeça longa)",
    videoUrl: V("rosca-inclinada-halteres"),
    equivalentId: "biceps-curl",
    cue: "O braço atrás da linha do tronco alonga a cabeça longa e aumenta o estímulo.",
    steps: [
      "Banco a 60 graus, braços pendendo livres.",
      "Suba supinando o punho.",
      "Contraia no topo por 1 segundo.",
      "Desça até a extensão completa.",
    ],
    mistakes: ["Levantar o cotovelo à frente.", "Cortar a amplitude final."],
  },
  {
    id: "cable-crunch",
    name: "Abdominal na Polia Alta",
    group: "Core",
    muscle: "Reto abdominal",
    videoUrl: V("abdominal-polia-alta"),
    equivalentId: "plank",
    cue: "Flexione a coluna aproximando as costelas do quadril, sem puxar com o braço.",
    steps: [
      "Ajoelhado de frente à polia, corda ao lado da cabeça.",
      "Flexione a coluna levando os cotovelos às coxas.",
      "Contraia 1 segundo no encurtamento.",
      "Retorne controlado sem perder a tensão.",
    ],
    mistakes: ["Movimentar apenas o quadril.", "Puxar a corda com os braços."],
  },
  {
    id: "plank",
    name: "Prancha Abdominal com Peso",
    group: "Core",
    muscle: "Core anterior",
    videoUrl: V("prancha-abdominal-peso"),
    equivalentId: "cable-crunch",
    cue: "Retroverta o quadril e mantenha o glúteo contraído durante todo o tempo.",
    steps: [
      "Apoie antebraços e pontas dos pés.",
      "Alinhe orelha, ombro, quadril e tornozelo.",
      "Contraia glúteo e abdômen.",
      "Respire de forma contínua durante o tempo alvo.",
    ],
    mistakes: ["Quadril alto demais.", "Lombar afundando."],
  },
];

const set = (reps: number, previous: string, count: number) =>
  Array.from({ length: count }, () => ({ reps, previous }));

export const DEFAULT_ROUTINE: Routine = {
  id: "meso-hipertrofia-01",
  name: "Hipertrofia Progressiva — Bloco A",
  createdAt: new Date("2026-09-01T08:00:00Z").toISOString(),
  mesocycle: "Mesociclo de Hipertrofia",
  week: 1,
  totalWeeks: 12,
  days: [
    {
      id: "seg",
      label: "Seg",
      focus: "Peito, Ombro Lateral & Tríceps",
      estimatedMinutes: "45-50 min",
      exercises: [
        { exerciseId: "bench-press", sets: set(10, "24 kg × 10", 4), restSeconds: 120 },
        { exerciseId: "incline-db-press", sets: set(12, "16 kg × 12", 4), restSeconds: 90 },
        { exerciseId: "lateral-raise", sets: set(15, "8 kg × 15", 4), restSeconds: 60 },
        { exerciseId: "triceps-rope", sets: set(12, "22 kg × 12", 4), restSeconds: 60 },
      ],
    },
    {
      id: "ter",
      label: "Ter",
      focus: "Costas, Trapézio & Bíceps",
      estimatedMinutes: "50-55 min",
      exercises: [
        { exerciseId: "lat-pulldown", sets: set(10, "45 kg × 10", 4), restSeconds: 120 },
        { exerciseId: "seated-row", sets: set(12, "40 kg × 12", 4), restSeconds: 90 },
        { exerciseId: "pull-up", sets: set(8, "assist 20 kg × 8", 3), restSeconds: 120 },
        { exerciseId: "incline-curl", sets: set(12, "10 kg × 12", 3), restSeconds: 60 },
      ],
    },
    {
      id: "qua",
      label: "Qua",
      focus: "Quadríceps, Glúteo & Core",
      estimatedMinutes: "55-60 min",
      exercises: [
        { exerciseId: "barbell-squat", sets: set(8, "60 kg × 8", 4), restSeconds: 180 },
        { exerciseId: "hack-squat", sets: set(12, "70 kg × 12", 3), restSeconds: 120 },
        { exerciseId: "romanian-deadlift", sets: set(10, "50 kg × 10", 3), restSeconds: 120 },
        { exerciseId: "cable-crunch", sets: set(15, "25 kg × 15", 3), restSeconds: 60 },
      ],
    },
    {
      id: "qui",
      label: "Qui",
      focus: "Ombro Completo & Tríceps",
      estimatedMinutes: "40-45 min",
      exercises: [
        { exerciseId: "machine-press", sets: set(10, "35 kg × 10", 4), restSeconds: 90 },
        { exerciseId: "cable-lateral-raise", sets: set(15, "6 kg × 15", 4), restSeconds: 60 },
        { exerciseId: "triceps-french", sets: set(12, "14 kg × 12", 3), restSeconds: 75 },
        { exerciseId: "plank", sets: set(45, "45 s × 3", 3), restSeconds: 45 },
      ],
    },
    {
      id: "sex",
      label: "Sex",
      focus: "Posterior de Coxa & Peito Alto",
      estimatedMinutes: "50-55 min",
      exercises: [
        { exerciseId: "romanian-deadlift", sets: set(10, "52 kg × 10", 4), restSeconds: 150 },
        { exerciseId: "leg-curl", sets: set(12, "30 kg × 12", 4), restSeconds: 90 },
        { exerciseId: "incline-db-press", sets: set(10, "18 kg × 10", 4), restSeconds: 90 },
        { exerciseId: "biceps-curl", sets: set(12, "20 kg × 12", 3), restSeconds: 60 },
      ],
    },
    {
      id: "sab",
      label: "Sáb",
      focus: "Full Body Metabólico & Core",
      estimatedMinutes: "35-40 min",
      exercises: [
        { exerciseId: "hack-squat", sets: set(15, "55 kg × 15", 3), restSeconds: 75 },
        { exerciseId: "seated-row", sets: set(15, "35 kg × 15", 3), restSeconds: 60 },
        { exerciseId: "machine-press", sets: set(15, "28 kg × 15", 3), restSeconds: 60 },
        { exerciseId: "cable-crunch", sets: set(20, "20 kg × 20", 3), restSeconds: 45 },
      ],
    },
  ],
};

export const DEFAULT_CONFIG: AdminConfig = {
  apiKey: "",
  model: "gpt-4o-mini",
  systemPrompt: `Você é o Treinador HyperFlow Pro, especialista em fisiologia do exercício e periodização.
Regras científicas:
1. Monte mesociclos de 12 semanas com progressão de carga dupla (repetição e depois carga).
2. Volume semanal entre 10 e 20 séries por grupo muscular treinado.
3. Priorize exercícios compostos no início da sessão e isoladores no final.
4. Descanso: 120-180s para compostos pesados, 45-90s para isoladores.
5. Use apenas exercícios presentes no catálogo fornecido e respeite restrições articulares informadas.
6. Para cada exercício, inclua uma dica biomecânica curta e objetiva em português.`,
};

export const DAILY_QUOTES: string[] = [
  "A consistência silenciosa supera o entusiasmo barulhento. Hoje é dia de carga máxima.",
  "Você não precisa de motivação. Precisa de disciplina e de mais uma repetição limpa.",
  "O corpo obedece à mente que decidiu antes de entrar na academia.",
  "Dor controlada é informação. Dor descontrolada é aviso. Aprenda a diferença.",
  "Ninguém vê as séries que você fez às 6 da manhã. O espelho vê.",
  "Treine hoje o corpo que vai te carregar aos 70 anos.",
  "Volume sem técnica é apenas fadiga caríssima. Execute com precisão.",
  "O que é fácil hoje foi impossível há doze semanas. Continue.",
  "Descanso é parte do treino, não uma pausa nele.",
  "Cada repetição controlada é um voto para a pessoa que você quer ser.",
  "A carga na barra é honesta: ela só sobe quando você merece.",
  "Domine o básico até que o básico pareça arte.",
];
